# travis.yml
language: python
sudo: required

cache: pip

python:
  - "3.6"

services:
  - docker

env:
  - COMPOSE_VERSION=1.23.1

before_install:
  # Stop Travis-CI postgresql,use docker integration instead
  - sudo /etc/init.d/postgresql stop
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

install:
  # Assist with ci test debugging:
  #- DEBUG=1
  # Build freeradius-django
  - docker build --pull --no-cache -t 2stacks/freeradius-django .
  # Build django container
  - cp ./scripts/local_settings.py ./django-freeradius/tests/
  - docker-compose build --pull

before_script:
  - image="2stacks/freeradius-django"
  - docker inspect "$image"
  - sudo chown root:70 ./certs/postgres/*
  - sudo chmod 640 ./certs/postgres/server.key

script: ./scripts/run-tests.sh

notifications:
  email:
    - 2stacks@2stacks.net