# travis.yml
language: python
sudo: required

cache: pip

python:
  - "3.6"

services:
  - docker

env:
  - COMPOSE_VERSION=1.23.1 DJANGO="django>=2.1,<2.2" DATABASE_URL='psql://debug:debug@127.0.0.1:5432/radius'

before_install:
  # Stop Travis-CI postgresql,use docker integration instead
  - sudo /etc/init.d/postgresql stop
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - git clone --depth 1 https://github.com/2stacks/django-freeradius.git
  - pip install -U pip wheel
  - pip install --no-cache-dir -U -r ./django-freeradius/requirements-test.txt

install:
  # Assist with ci test debugging:
  - DEBUG=1
  - docker build --pull --no-cache -t 2stacks/freeradius-django .
  - pip install $DJANGO
  - cd ./django-freeradius
  - python setup.py -q develop
  - cd ..
  # Temporary: remove when openwisp-utils 0.3 is released
  - pip install -U https://github.com/openwisp/openwisp-utils/tarball/master

before_script:
  - image="2stacks/freeradius-django"
  - docker inspect "$image"
  - sudo chown root:70 ./certs/postgres/*
  - sudo chmod 640 ./certs/postgres/server.key

script: ./scripts/run-tests.sh

notifications:
  email:
    - 2stacks@2stacks.net